spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/class
spring.jpa.show-sql=true
spring.datasource.password=theo123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=update
